namespace: microserviceB

public: web:3000

services:
  web:
    image: node:4
    volumes:
      - .:/microserviceB
    working_dir: /microserviceB
    environment:
      - "MICROSERVICEC_ENDPOINT=http://microservicec:3000"
    command: [npm, start]

dependencies:
  - microserviceC

setup:
  - npm install
