namespace: microserviceB

public:
  - web

services:
  web:
    image: node:4
    volumes:
      - .:/microserviceB
    working_dir: /microserviceB
    environment:
      - "MICROSERVICEC_ENDPOINT=http://microserviceC"
    command: [npm, start]

dependencies:
  - microserviceC

setup:
  - npm install
