namespace: microserviceB

public:
  - web

services:
  web:
    image: node:4
    ports:
      - "3000:3000"
    volumes:
      - ..:/microserviceB
    working_dir: /microserviceB
    command: [npm, start]

setup:
  - cd .. && npm install
